/*
-------------
-- Categories
-------------

CREATE TABLE "PUBLIC"."CATEGORIES"
(
  CATEGORY_ID bigint PRIMARY KEY NOT NULL,
  NAME varchar NOT NULL,
  USER_ID bigint NOT NULL,
  PARENT_ID bigint
)
;
ALTER TABLE "PUBLIC"."CATEGORIES"
ADD CONSTRAINT FK_QCXM4G5IXFHI2MYT8RTVQ2HU1
FOREIGN KEY (USER_ID)
REFERENCES "PUBLIC"."USERS"(USER_ID)
;
ALTER TABLE "PUBLIC"."CATEGORIES"
ADD CONSTRAINT FK_3RWQUSFA6OFWWU7KDL340A3OC
FOREIGN KEY (PARENT_ID)
REFERENCES "PUBLIC"."CATEGORIES"(CATEGORY_ID)
;
CREATE INDEX SYS_IDX_10119 ON "PUBLIC"."CATEGORIES"(PARENT_ID)
;
CREATE INDEX SYS_IDX_10143 ON "PUBLIC"."CATEGORIES"(USER_ID)
;
CREATE UNIQUE INDEX SYS_IDX_SYS_PK_10112_10115 ON "PUBLIC"."CATEGORIES"(CATEGORY_ID)
;

-----------
-- Expenses
-----------

CREATE TABLE "PUBLIC"."EXPENSES"
(
  EXPENSE_ID bigint PRIMARY KEY NOT NULL,
  AMOUNT double NOT NULL,
  MERCHANT varchar,
  CATEGORY_ID bigint NOT NULL,
  TRANSACTION_ID bigint NOT NULL
)
;
ALTER TABLE "PUBLIC"."EXPENSES"
ADD CONSTRAINT FK_SO8OVHDRC1716RHFCB8AGQWRP
FOREIGN KEY (TRANSACTION_ID)
REFERENCES "PUBLIC"."TRANSACTIONS"(TRANSACTION_ID)
;
ALTER TABLE "PUBLIC"."EXPENSES"
ADD CONSTRAINT FK_NFOEMIYT02GUM8RM4B05BHYAX
FOREIGN KEY (CATEGORY_ID)
REFERENCES "PUBLIC"."CATEGORIES"(CATEGORY_ID)
;
CREATE UNIQUE INDEX SYS_IDX_SYS_PK_10126_10130 ON "PUBLIC"."EXPENSES"(EXPENSE_ID)
;
CREATE INDEX SYS_IDX_10137 ON "PUBLIC"."EXPENSES"(TRANSACTION_ID)
;
CREATE INDEX SYS_IDX_10135 ON "PUBLIC"."EXPENSES"(CATEGORY_ID)
;

---------------
-- Transactions
---------------

CREATE TABLE "PUBLIC"."TRANSACTIONS"
(
  TRANSACTION_ID bigint PRIMARY KEY NOT NULL,
  AMOUNT double NOT NULL,
  EFFECTIVE_DATE timestamp NOT NULL,
  DESCRIPTION varchar NOT NULL,
  NOTES varchar,
  ACCOUNT_ID bigint NOT NULL
)
;
ALTER TABLE "PUBLIC"."TRANSACTIONS"
ADD CONSTRAINT FK_4436PV0BRNSTC61R0X3PG18IS
FOREIGN KEY (ACCOUNT_ID)
REFERENCES "PUBLIC"."ACCOUNTS"(ACCOUNT_ID)
;
CREATE UNIQUE INDEX SYS_IDX_SYS_PK_10098_10103 ON "PUBLIC"."TRANSACTIONS"(TRANSACTION_ID)
;
CREATE INDEX SYS_IDX_10109 ON "PUBLIC"."TRANSACTIONS"(ACCOUNT_ID)
;

--------
-- Users
--------

CREATE TABLE "PUBLIC"."USERS"
(
  USER_ID bigint PRIMARY KEY NOT NULL,
  NAME varchar
)
;
CREATE UNIQUE INDEX SYS_IDX_SYS_PK_10122_10123 ON "PUBLIC"."USERS"(USER_ID)
;
*/

-- ALTER TABLE "PUBLIC"."ACCOUNTS"
--ADD COLUMN "PARENT_ID" BIGINT NULL
--;
--ALTER TABLE "PUBLIC"."ACCOUNTS"
--ADD CONSTRAINT FK_ACCOUNTS
--FOREIGN KEY (PARENT_ID)
--REFERENCES "PUBLIC"."ACCOUNTS"(ACCOUNT_ID)
--;
--CREATE INDEX SYS_IDX_10119 ON "PUBLIC"."ACCOUNTS"(PARENT_ID)
--;